export const RESET_CART = 'RESET_CART';
export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const CUSTOM_ORDER_ADD_TO_CART = 'CUSTOM_ORDER_ADD_TO_CART';
export const CUSTOM_ORDER_REMOVE_FROM_CART = 'CUSTOM_ORDER_REMOVE_FROM_CART';
export const CHECKOUT_ORDER_REQUEST = 'CHECKOUT_ORDER_REQUEST';
export const CHECKOUT_ORDER_SUCCESS = 'CHECKOUT_ORDER_SUCCESS';
export const CHECKOUT_ORDER_FAILURE = 'CHECKOUT_ORDER_FAILURE';
