// Meta Data
export const META_DATA_REQUEST = 'META_DATA_REQUEST';
export const META_DATA_SUCCESS = 'META_DATA_SUCCESS';
export const META_DATA_FAIL = 'META_DATA_FAIL';
// Suggested Order
export const SUGGESTED_PRODUCT_REQUEST = 'SUGGESTED_PRODUCT_REQUEST';
export const SUGGESTED_PRODUCT_SUCCESS = 'SUGGESTED_PRODUCT_SUCCESS';
export const SUGGESTED_PRODUCT_FAIL = 'SUGGESTED_PRODUCT_FAIL';
