// GRAPH SELECTION

export const GRAPH_SELECTION_REQUEST = 'GRAPH_SELECTION_REQUEST';
export const GRAPH_SELECTION_SUCCESS = 'GRAPH_SELECTION_SUCCESS';
export const GRAPH_SELECTION_FAIL = 'GRAPH_SELECTION_FAIL';

// GRAPH CART
export const GRAPH_CHART_REQUEST = 'GRAPH_CHART_REQUEST';
export const GRAPH_CHART_SUCCESS = 'GRAPH_CHART_SUCCESS';
export const GRAPH_CHART_FAIL = 'GRAPH_CHART_FAIL';
