export const ORDER_NOTIFICATION_REQUEST = 'ORDER_NOTIFICATION_REQUEST';
export const ORDER_NOTIFICATION_SUCCESS = 'ORDER_NOTIFICATION_SUCCESS';
export const ORDER_NOTIFICATION_FAIL = 'ORDER_NOTIFICATION_FAIL';
