// SEARCH BY BRAND
export const BRAND_FILTER_REQUEST = 'BRAND_FILTER_REQUEST';
export const BRAND_FILTER_SUCCESS = 'BRAND_FILTER_SUCCESS';
export const BRAND_FILTER_FAIL = 'BRAND_FILTER_FAIL';
// SEARCH BY CATEGORY
export const CATEGORY_FILTER_REQUEST = 'CATEGORY_FILTER_REQUEST';
export const CATEGORY_FILTER_SUCCESS = 'CATEGORY_FILTER_SUCCESS';
export const CATEGORY_FILTER_FAIL = 'CATEGORY_FILTER_FAIL';
